// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadStateEvent = { id: string, status: string, error: string | null, fileName?: string, };
