// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaHandoffPhase } from "./MediaHandoffPhase";

export type ExtensionMediaDiscoveryUpdate = { request_id?: string, handoff_id: string, phase: MediaHandoffPhase, urls: Array<string>, referer: string | null, headers: string | null, };
