// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TorrentFileSelectionEntry } from "./TorrentFileSelectionEntry";

export type TorrentFileSelectionSnapshot = { files: Array<TorrentFileSelectionEntry>, };
