// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TorrentPeer } from "./TorrentPeer";

export type TorrentPeerDiagnostics = { listedPeers: number, listedSeeders: number, peers: Array<TorrentPeer>, truncated: boolean, };
