// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TorrentFileProgress = { index: number, relativePath: string, length: number, completedLength: number, selected: boolean, };
