// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TorrentFileProgress } from "./TorrentFileProgress";

export type TorrentFileProgressSnapshot = { files: Array<TorrentFileProgress>, };
